Repository upasanadeka/Text-Animation, pull requests merged in 2020-10, with the labels that each got.

#4 Update README.md
  README.md
Labels: Hacktoberfest, good first issue, hacktoberfest2020

#6 Add Animated Cursor With Hover Effect 😁
  index.html
  style.css
Labels: Hacktoberfest, good first issue, hacktoberfest-accepted, hacktoberfest2020

#7 Add my name 🐱‍🏍
  README.md
Labels: hacktoberfest-accepted

#9 Added Dark Mode :)
  README.md
  index.html
  style.css
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2020
